### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by btskinner**
Per our conversations about wanting other researchers to feel comfortable contributing, I initialized a code of conduct using a standard template. While I do not expect to have any issues, I think a code of conduct is a good thing to have for any project that invites external contributions.

I listed everyone as a potential contact for enforcement of code violations (lines 60-64), but gave only gave my email. We can keep it with just me, have all core members, or something in between.

To facilitate this process, if everyone could just respond with their personal preference, I can adjust the list accordingly. I see these as the options:

1. Only Ben is a contact (not important that it's me, per se, but just have one person)
2. You **DO NOT** want to be a contact (and we'll remove your name from the list)
3. You **DO** want to be a contact and have your email listed

### CODE REVIEW

**Comment by wdoyle42** [comment]
I agree with the terms of the code of conduct and I'm in favor of merging the pull request.

**Comment by btskinner** [comment]
@wdoyle42, do you want to be listed with email or just have me?

**Comment by ozanj** [comment]
I like the code of conduct.

I would rather not have my email address listed as potential referee for violations of code of conduct.

I think we should add a few lines to the extent that coding is hard and we want our community to treat questions or deviations from standards of coding practice with kindness and explanation rather than score and ridicule [some random bullet points i type up here:]

- this project is being built by and targeted to researchers who are not coders. 
- coding is hard. further, coding communities have lots of norms about how things should be done that can feel cryptic and unwelcoming to newcomers. 
- in the wild, deviations from these norms are met with ridicule and snark. for example, posing a question to an online community but not using standard protocol (e.g., provide working example) or not following standard protocol for use of github.
- in our unrollment_proj community, a goal is to help researchers learn the coding skills and coding community standards of practice. we pledge that questions by community members and deviations from standards of practice will never never be met with hostility. rather, we will be kind and point community members to helpful resources.

**Comment by ksalazar3** [comment]
I am in agreement with what is currently on code of conduct + Ozan's additions!

**Comment by btskinner** [comment]
I've included a new section at the top that integrates @ozanj's suggestions and added a small bit to the **Pledge** section. Finally, I've slightly rewritten the **Enforcement** part to explicitly call me out with address as a point of contact, but note that any core contributor can be contacted, with links to your websites.

Thoughts?

**Comment by mpatricia01** [comment]
Agree with code of conduct + Ozan's comments + Ben's suggestion to be the point of contact and include our information if folks want to contact us as well.

**Comment by ozanj** [comment]
this revised code of conduct looks great ben!

I'm assigned as reviewer on this issue. what does that mean and what should I do?

**Comment by btskinner** [comment]
@ozanj, I'm still getting the hang of reviewers / assignees in groups. But I think you've done your review by replying here. It seems everyone is on board, so I'm going to merge the code of conduct into the `master` branch. We can edit later as necessary.

**Pull request merged**
